version: '3.8'
services:
  app:
    image: php:8.2-fpm
    container_name: kryppt_php
    volumes:
      - ./data:/var/www
    working_dir: /var/www
    networks:
      - kryppt_network

  web:
    image: nginx:stable-alpine
    container_name: kryppt_nginx
    ports:
      - "8000:80"
    volumes:
      - ./data/laravel-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - kryppt_network

  db:
    image: mariadb:10.6
    container_name: kryppt_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kryppt
      MYSQL_USER: kryppt
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kryppt_network

  composer:
    image: composer:2
    container_name: kryppt_composer
    volumes:
      - ./data:/var/www
    working_dir: /var/www
    networks:
      - kryppt_network

volumes:
  db_data:

networks:
  kryppt_network:
    driver: bridge
